project_id = "jasqctuzeznwdtbcuixn"

[functions.embed-chunks]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.get-usage-stats]
verify_jwt = false

[functions.submit-chat-feedback]
verify_jwt = false
