// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const SUPABASE_UNAVAILABLE_MESSAGE =
  'Este ambiente ainda está finalizando a conexão principal da CLARA. Assim que ela for concluída, o acesso completo volta a ficar disponível.';

type UnavailableQueryResponse = {
  count: number;
  data: null;
  error: Error;
  status: number;
  statusText: string;
};

function createUnavailableError() {
  return new Error(SUPABASE_UNAVAILABLE_MESSAGE);
}

function createUnavailableResponse(overrides: Partial<UnavailableQueryResponse> = {}): UnavailableQueryResponse {
  return {
    count: 0,
    data: null,
    error: createUnavailableError(),
    status: 503,
    statusText: 'Supabase not configured',
    ...overrides,
  };
}

function createUnavailableQueryBuilder() {
  const response = Promise.resolve(createUnavailableResponse());

  const builder = {
    delete: () => builder,
    eq: () => builder,
    finally: response.finally.bind(response),
    insert: () => builder,
    order: () => builder,
    select: () => builder,
    single: () => builder,
    then: response.then.bind(response),
    update: () => builder,
    catch: response.catch.bind(response),
  };

  return builder;
}

function createUnavailableSupabaseClient(): SupabaseClient<Database> {
  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe() {},
          },
        },
      }),
      signInWithOAuth: async () =>
        ({
          data: { provider: undefined, url: null },
          error: createUnavailableError(),
        }),
      signInWithPassword: async () =>
        ({
          data: { session: null, user: null },
          error: createUnavailableError(),
        }),
      signOut: async () => ({ error: null }),
    },
    from: () => createUnavailableQueryBuilder(),
    functions: {
      invoke: async () => createUnavailableResponse(),
    },
    storage: {
      from: () => ({
        download: async () => createUnavailableResponse(),
        remove: async () => ({ data: [], error: createUnavailableError() }),
        upload: async () => createUnavailableResponse(),
      }),
    },
  } as unknown as SupabaseClient<Database>;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        flowType: 'pkce',
      },
    })
  : createUnavailableSupabaseClient();
